travis:
  secure:
    BINSTAR_TOKEN: F6ILnGnADnfVvWDDWpGh1tjAjTl7tjgqRcJ302O4nEZ2oezh7lnEmEn+O2dozQrG5v4iYAXUF2Y6hdZTZkmZMpIm8yMSFWeMRWqt5hXBTtqqheBQRszkvLcSOFbYGvuF1avyjwEf+zRVu1WdtXVWRHyZCED4N4EOVSVSsAEyZuWCj6NLt7CAAb4uAXDVcY0vgCeNS9KAYaEp/QQoGXnRUiRkFWyA65qVqPzyerA7ns8EvZUOMLnLAJg6dD+XaYxCinPV2a9fONPjnnEgvSZtJTT5iuAU/y/JaCHKIhhCutJvZgvDdG2qGF08CfYaJg9cFGS/mrO0FcRmje5gxv2nUBu+ymyVfLoBA1AEMmLT04BvrCPz+43PkqoPs7WF2AlCq4QEIPwZGJi9Xaw2EO2y+32mA6PDcYoAnZFDrcJCgU40/K+hyIaBZRNIpDLPbFJzw5JQNKA0ise/vdm6dhsdvvuL5DxXV7YKYN0GGtaahq00OX/xHnsdWgGKgAMgOxFsXJQZL8BIrROMy055dpLmh8VOsdWGs76lqQtFTUbijOuicmLjszfVvTbFG8D/vKtREMXgt6thBSTB9Zv4HVEFJ3VH/q3nK9JC/IXhfwlMIjnzp1JhpM5IWv51UyVW2EXOVBbWwFwbkhtBKIfEfHh+B7tA4q/54eRbZceGuawE0xw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
